apiVersion: v1
kind: Service
metadata:
  name: message-broker-external
spec:
  selector:
    app: message-broker
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30008
  type: NodePort
